package com.yc.sale.bean;

public class CusCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cus_customer.cus_id
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    private Integer cusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cus_customer.cus_name
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    private String cusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cus_customer.cus_addr
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    private String cusAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cus_customer.cus_id
     *
     * @return the value of cus_customer.cus_id
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public Integer getCusId() {
        return cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cus_customer.cus_id
     *
     * @param cusId the value for cus_customer.cus_id
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cus_customer.cus_name
     *
     * @return the value of cus_customer.cus_name
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public String getCusName() {
        return cusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cus_customer.cus_name
     *
     * @param cusName the value for cus_customer.cus_name
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void setCusName(String cusName) {
        this.cusName = cusName == null ? null : cusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cus_customer.cus_addr
     *
     * @return the value of cus_customer.cus_addr
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public String getCusAddr() {
        return cusAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cus_customer.cus_addr
     *
     * @param cusAddr the value for cus_customer.cus_addr
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void setCusAddr(String cusAddr) {
        this.cusAddr = cusAddr == null ? null : cusAddr.trim();
    }
}