package com.yc.sale.bean;

import java.util.ArrayList;
import java.util.List;

public class SaleOrderLineExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public SaleOrderLineExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOdlIdIsNull() {
            addCriterion("odl_id is null");
            return (Criteria) this;
        }

        public Criteria andOdlIdIsNotNull() {
            addCriterion("odl_id is not null");
            return (Criteria) this;
        }

        public Criteria andOdlIdEqualTo(Integer value) {
            addCriterion("odl_id =", value, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlIdNotEqualTo(Integer value) {
            addCriterion("odl_id <>", value, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlIdGreaterThan(Integer value) {
            addCriterion("odl_id >", value, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("odl_id >=", value, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlIdLessThan(Integer value) {
            addCriterion("odl_id <", value, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlIdLessThanOrEqualTo(Integer value) {
            addCriterion("odl_id <=", value, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlIdIn(List<Integer> values) {
            addCriterion("odl_id in", values, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlIdNotIn(List<Integer> values) {
            addCriterion("odl_id not in", values, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlIdBetween(Integer value1, Integer value2) {
            addCriterion("odl_id between", value1, value2, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlIdNotBetween(Integer value1, Integer value2) {
            addCriterion("odl_id not between", value1, value2, "odlId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdIsNull() {
            addCriterion("odl_order_id is null");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdIsNotNull() {
            addCriterion("odl_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdEqualTo(Integer value) {
            addCriterion("odl_order_id =", value, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdNotEqualTo(Integer value) {
            addCriterion("odl_order_id <>", value, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdGreaterThan(Integer value) {
            addCriterion("odl_order_id >", value, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("odl_order_id >=", value, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdLessThan(Integer value) {
            addCriterion("odl_order_id <", value, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("odl_order_id <=", value, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdIn(List<Integer> values) {
            addCriterion("odl_order_id in", values, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdNotIn(List<Integer> values) {
            addCriterion("odl_order_id not in", values, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("odl_order_id between", value1, value2, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("odl_order_id not between", value1, value2, "odlOrderId");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameIsNull() {
            addCriterion("odl_product_name is null");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameIsNotNull() {
            addCriterion("odl_product_name is not null");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameEqualTo(String value) {
            addCriterion("odl_product_name =", value, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameNotEqualTo(String value) {
            addCriterion("odl_product_name <>", value, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameGreaterThan(String value) {
            addCriterion("odl_product_name >", value, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("odl_product_name >=", value, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameLessThan(String value) {
            addCriterion("odl_product_name <", value, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameLessThanOrEqualTo(String value) {
            addCriterion("odl_product_name <=", value, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameLike(String value) {
            addCriterion("odl_product_name like", value, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameNotLike(String value) {
            addCriterion("odl_product_name not like", value, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameIn(List<String> values) {
            addCriterion("odl_product_name in", values, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameNotIn(List<String> values) {
            addCriterion("odl_product_name not in", values, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameBetween(String value1, String value2) {
            addCriterion("odl_product_name between", value1, value2, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductNameNotBetween(String value1, String value2) {
            addCriterion("odl_product_name not between", value1, value2, "odlProductName");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceIsNull() {
            addCriterion("odl_product_price is null");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceIsNotNull() {
            addCriterion("odl_product_price is not null");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceEqualTo(Double value) {
            addCriterion("odl_product_price =", value, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceNotEqualTo(Double value) {
            addCriterion("odl_product_price <>", value, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceGreaterThan(Double value) {
            addCriterion("odl_product_price >", value, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("odl_product_price >=", value, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceLessThan(Double value) {
            addCriterion("odl_product_price <", value, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceLessThanOrEqualTo(Double value) {
            addCriterion("odl_product_price <=", value, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceIn(List<Double> values) {
            addCriterion("odl_product_price in", values, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceNotIn(List<Double> values) {
            addCriterion("odl_product_price not in", values, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceBetween(Double value1, Double value2) {
            addCriterion("odl_product_price between", value1, value2, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductPriceNotBetween(Double value1, Double value2) {
            addCriterion("odl_product_price not between", value1, value2, "odlProductPrice");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountIsNull() {
            addCriterion("odl_product_count is null");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountIsNotNull() {
            addCriterion("odl_product_count is not null");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountEqualTo(Integer value) {
            addCriterion("odl_product_count =", value, "odlProductCount");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountNotEqualTo(Integer value) {
            addCriterion("odl_product_count <>", value, "odlProductCount");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountGreaterThan(Integer value) {
            addCriterion("odl_product_count >", value, "odlProductCount");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("odl_product_count >=", value, "odlProductCount");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountLessThan(Integer value) {
            addCriterion("odl_product_count <", value, "odlProductCount");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountLessThanOrEqualTo(Integer value) {
            addCriterion("odl_product_count <=", value, "odlProductCount");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountIn(List<Integer> values) {
            addCriterion("odl_product_count in", values, "odlProductCount");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountNotIn(List<Integer> values) {
            addCriterion("odl_product_count not in", values, "odlProductCount");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountBetween(Integer value1, Integer value2) {
            addCriterion("odl_product_count between", value1, value2, "odlProductCount");
            return (Criteria) this;
        }

        public Criteria andOdlProductCountNotBetween(Integer value1, Integer value2) {
            addCriterion("odl_product_count not between", value1, value2, "odlProductCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_order_line
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 14 16:13:25 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}