package com.yc.sale.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SaleOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public SaleOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOdrIdIsNull() {
            addCriterion("odr_id is null");
            return (Criteria) this;
        }

        public Criteria andOdrIdIsNotNull() {
            addCriterion("odr_id is not null");
            return (Criteria) this;
        }

        public Criteria andOdrIdEqualTo(Integer value) {
            addCriterion("odr_id =", value, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrIdNotEqualTo(Integer value) {
            addCriterion("odr_id <>", value, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrIdGreaterThan(Integer value) {
            addCriterion("odr_id >", value, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("odr_id >=", value, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrIdLessThan(Integer value) {
            addCriterion("odr_id <", value, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrIdLessThanOrEqualTo(Integer value) {
            addCriterion("odr_id <=", value, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrIdIn(List<Integer> values) {
            addCriterion("odr_id in", values, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrIdNotIn(List<Integer> values) {
            addCriterion("odr_id not in", values, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrIdBetween(Integer value1, Integer value2) {
            addCriterion("odr_id between", value1, value2, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrIdNotBetween(Integer value1, Integer value2) {
            addCriterion("odr_id not between", value1, value2, "odrId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdIsNull() {
            addCriterion("odr_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdIsNotNull() {
            addCriterion("odr_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdEqualTo(Integer value) {
            addCriterion("odr_customer_id =", value, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdNotEqualTo(Integer value) {
            addCriterion("odr_customer_id <>", value, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdGreaterThan(Integer value) {
            addCriterion("odr_customer_id >", value, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("odr_customer_id >=", value, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdLessThan(Integer value) {
            addCriterion("odr_customer_id <", value, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("odr_customer_id <=", value, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdIn(List<Integer> values) {
            addCriterion("odr_customer_id in", values, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdNotIn(List<Integer> values) {
            addCriterion("odr_customer_id not in", values, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("odr_customer_id between", value1, value2, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("odr_customer_id not between", value1, value2, "odrCustomerId");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameIsNull() {
            addCriterion("odr_customer_name is null");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameIsNotNull() {
            addCriterion("odr_customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameEqualTo(String value) {
            addCriterion("odr_customer_name =", value, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameNotEqualTo(String value) {
            addCriterion("odr_customer_name <>", value, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameGreaterThan(String value) {
            addCriterion("odr_customer_name >", value, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("odr_customer_name >=", value, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameLessThan(String value) {
            addCriterion("odr_customer_name <", value, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("odr_customer_name <=", value, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameLike(String value) {
            addCriterion("odr_customer_name like", value, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameNotLike(String value) {
            addCriterion("odr_customer_name not like", value, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameIn(List<String> values) {
            addCriterion("odr_customer_name in", values, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameNotIn(List<String> values) {
            addCriterion("odr_customer_name not in", values, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameBetween(String value1, String value2) {
            addCriterion("odr_customer_name between", value1, value2, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrCustomerNameNotBetween(String value1, String value2) {
            addCriterion("odr_customer_name not between", value1, value2, "odrCustomerName");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrIsNull() {
            addCriterion("odr_deliver_addr is null");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrIsNotNull() {
            addCriterion("odr_deliver_addr is not null");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrEqualTo(String value) {
            addCriterion("odr_deliver_addr =", value, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrNotEqualTo(String value) {
            addCriterion("odr_deliver_addr <>", value, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrGreaterThan(String value) {
            addCriterion("odr_deliver_addr >", value, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrGreaterThanOrEqualTo(String value) {
            addCriterion("odr_deliver_addr >=", value, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrLessThan(String value) {
            addCriterion("odr_deliver_addr <", value, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrLessThanOrEqualTo(String value) {
            addCriterion("odr_deliver_addr <=", value, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrLike(String value) {
            addCriterion("odr_deliver_addr like", value, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrNotLike(String value) {
            addCriterion("odr_deliver_addr not like", value, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrIn(List<String> values) {
            addCriterion("odr_deliver_addr in", values, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrNotIn(List<String> values) {
            addCriterion("odr_deliver_addr not in", values, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrBetween(String value1, String value2) {
            addCriterion("odr_deliver_addr between", value1, value2, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverAddrNotBetween(String value1, String value2) {
            addCriterion("odr_deliver_addr not between", value1, value2, "odrDeliverAddr");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateIsNull() {
            addCriterion("odr_order_date is null");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateIsNotNull() {
            addCriterion("odr_order_date is not null");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateEqualTo(Date value) {
            addCriterionForJDBCDate("odr_order_date =", value, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("odr_order_date <>", value, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateGreaterThan(Date value) {
            addCriterionForJDBCDate("odr_order_date >", value, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("odr_order_date >=", value, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateLessThan(Date value) {
            addCriterionForJDBCDate("odr_order_date <", value, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("odr_order_date <=", value, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateIn(List<Date> values) {
            addCriterionForJDBCDate("odr_order_date in", values, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("odr_order_date not in", values, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("odr_order_date between", value1, value2, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrOrderDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("odr_order_date not between", value1, value2, "odrOrderDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateIsNull() {
            addCriterion("odr_deliver_date is null");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateIsNotNull() {
            addCriterion("odr_deliver_date is not null");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateEqualTo(Date value) {
            addCriterionForJDBCDate("odr_deliver_date =", value, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("odr_deliver_date <>", value, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateGreaterThan(Date value) {
            addCriterionForJDBCDate("odr_deliver_date >", value, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("odr_deliver_date >=", value, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateLessThan(Date value) {
            addCriterionForJDBCDate("odr_deliver_date <", value, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("odr_deliver_date <=", value, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateIn(List<Date> values) {
            addCriterionForJDBCDate("odr_deliver_date in", values, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("odr_deliver_date not in", values, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("odr_deliver_date between", value1, value2, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrDeliverDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("odr_deliver_date not between", value1, value2, "odrDeliverDate");
            return (Criteria) this;
        }

        public Criteria andOdrStatusIsNull() {
            addCriterion("odr_status is null");
            return (Criteria) this;
        }

        public Criteria andOdrStatusIsNotNull() {
            addCriterion("odr_status is not null");
            return (Criteria) this;
        }

        public Criteria andOdrStatusEqualTo(String value) {
            addCriterion("odr_status =", value, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusNotEqualTo(String value) {
            addCriterion("odr_status <>", value, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusGreaterThan(String value) {
            addCriterion("odr_status >", value, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusGreaterThanOrEqualTo(String value) {
            addCriterion("odr_status >=", value, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusLessThan(String value) {
            addCriterion("odr_status <", value, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusLessThanOrEqualTo(String value) {
            addCriterion("odr_status <=", value, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusLike(String value) {
            addCriterion("odr_status like", value, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusNotLike(String value) {
            addCriterion("odr_status not like", value, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusIn(List<String> values) {
            addCriterion("odr_status in", values, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusNotIn(List<String> values) {
            addCriterion("odr_status not in", values, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusBetween(String value1, String value2) {
            addCriterion("odr_status between", value1, value2, "odrStatus");
            return (Criteria) this;
        }

        public Criteria andOdrStatusNotBetween(String value1, String value2) {
            addCriterion("odr_status not between", value1, value2, "odrStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_order
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 14 16:13:25 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}