package com.yc.sale.dao;

import com.yc.sale.bean.CusCustomer;
import com.yc.sale.bean.CusCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CusCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    long countByExample(CusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int deleteByExample(CusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int deleteByPrimaryKey(Integer cusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int insert(CusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int insertSelective(CusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    List<CusCustomer> selectByExample(CusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    CusCustomer selectByPrimaryKey(Integer cusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") CusCustomer record, @Param("example") CusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByExample(@Param("record") CusCustomer record, @Param("example") CusCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByPrimaryKeySelective(CusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cus_customer
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByPrimaryKey(CusCustomer record);
}