package com.yc.sale.dao;

import com.yc.sale.bean.SaleOrderLine;
import com.yc.sale.bean.SaleOrderLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SaleOrderLineMapper {
    
	
	//一对多查询 懒加载是调用此方法
	@Select("select * from sale_order_line where odl_order_id=#{id} ")
	public List<SaleOrderLine> selectByOrderId(int id);
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    long countByExample(SaleOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int deleteByExample(SaleOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int deleteByPrimaryKey(Integer odlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int insert(SaleOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int insertSelective(SaleOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    List<SaleOrderLine> selectByExample(SaleOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    SaleOrderLine selectByPrimaryKey(Integer odlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaleOrderLine record, @Param("example") SaleOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByExample(@Param("record") SaleOrderLine record, @Param("example") SaleOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByPrimaryKeySelective(SaleOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order_line
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByPrimaryKey(SaleOrderLine record);
}