package com.yc.sale.dao;

import com.yc.sale.bean.SaleOrder;
import com.yc.sale.bean.SaleOrderExample;
import java.util.List;

import org.apache.ibatis.annotations.Many;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.mapping.FetchType;

public interface SaleOrderMapper {
   
	//  一对多查询  ordeLines
	@Select("select * from sale_order where odr_id=#{id}")
	@Results(id="order_line",value={
			@Result(column="odr_id",property="odrId"),
			@Result(column="odr_id",property="ordeLines",many=@Many(fetchType=FetchType.LAZY,
			select="com.yc.sale.dao.SaleOrderLineMapper.selectByOrderId"))
	})
	public SaleOrder queryManyByOid(int id);
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    long countByExample(SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int deleteByExample(SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int deleteByPrimaryKey(Integer odrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int insert(SaleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int insertSelective(SaleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    List<SaleOrder> selectByExample(SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    SaleOrder selectByPrimaryKey(Integer odrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaleOrder record, @Param("example") SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByExample(@Param("record") SaleOrder record, @Param("example") SaleOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByPrimaryKeySelective(SaleOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByPrimaryKey(SaleOrder record);
}