package com.yc.sale.dao;

import com.yc.sale.bean.SaleProduct;
import com.yc.sale.bean.SaleProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    long countByExample(SaleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int deleteByExample(SaleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int deleteByPrimaryKey(Integer prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int insert(SaleProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int insertSelective(SaleProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    List<SaleProduct> selectByExample(SaleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    SaleProduct selectByPrimaryKey(Integer prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaleProduct record, @Param("example") SaleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByExample(@Param("record") SaleProduct record, @Param("example") SaleProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByPrimaryKeySelective(SaleProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_product
     *
     * @mbg.generated Wed Aug 14 16:13:25 CST 2019
     */
    int updateByPrimaryKey(SaleProduct record);
}